#!/bin/bash

echo "请按以下步骤操作："
echo ""
echo "1. 首先连接到VPS："
echo "   ssh root@45.149.156.216"
echo ""
echo "2. 连接成功后，逐行执行以下命令："
echo ""
echo "cd /var/www/research-dashboard"
echo "git pull origin main"
echo "cd frontend"
echo "rm -rf build node_modules/.cache"
echo "npm install"
echo "npm run build"
echo "rm -rf /var/www/html/*"
echo "cp -r build/* /var/www/html/"
echo "cd .."
echo "sudo systemctl restart nginx"
echo ""
echo "3. 执行完成后，清除浏览器缓存并刷新"