#!/bin/bash

# 紧急修复VPS上的缓存问题

echo "🚨 执行紧急修复..."
echo ""
echo "这个脚本会通过SSH连接到VPS并："
echo "1. 强制更新代码"
echo "2. 清理所有缓存"  
echo "3. 更新Nginx配置"
echo "4. 重新构建前端"
echo ""
echo "请在新的终端窗口执行以下命令："
echo ""
echo "ssh root@45.149.156.216 'bash -s' << 'ENDSSH'"
echo "cd /var/www/research-dashboard"
echo "git fetch --all"
echo "git reset --hard origin/main"
echo "cd frontend"
echo "rm -rf build node_modules/.cache"
echo "npm install"
echo "npm run build"
echo "rm -rf /var/www/html/*"
echo "cp -r build/* /var/www/html/"
echo "cd .."
echo "if [ -f deployment/nginx-fixed.conf ]; then"
echo "  sudo cp deployment/nginx-fixed.conf /etc/nginx/sites-available/research-dashboard"
echo "else"
echo "  sudo cp deployment/nginx.conf /etc/nginx/sites-available/research-dashboard"
echo "fi"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo "echo '✅ 修复完成！'"
echo "ENDSSH"