#!/bin/bash

echo "修复VPS上的Git冲突和权限问题"
echo "==========================="
echo ""
echo "请在VPS上执行以下命令："
echo ""
echo "# 1. 强制重置到最新版本（会丢失本地未提交的更改）"
echo "cd /var/www/research-dashboard"
echo "git fetch --all"
echo "git reset --hard origin/main"
echo ""
echo "# 2. 更新Nginx配置（使用sudo）"
echo "sudo cp deployment/nginx.conf /etc/nginx/sites-available/research-dashboard"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "# 3. 重新构建前端"
echo "cd frontend"
echo "rm -rf build node_modules/.cache"
echo "npm install && npm run build"
echo "rm -rf /var/www/html/*"
echo "cp -r build/* /var/www/html/"
echo ""
echo "# 4. 确认完成"
echo "echo '✅ 修复完成！'"