#!/bin/bash

# 检查VPS上的迁移执行状态

echo "=== 检查VPS迁移状态 ==="
echo "请在VPS上执行以下命令："
echo ""
echo "cd /var/www/research-dashboard/backend"
echo ""
echo "# 1. 检查迁移历史"
echo "sqlite3 data/research_dashboard_prod.db \"SELECT version, executed_at FROM migration_history ORDER BY executed_at DESC LIMIT 10;\""
echo ""
echo "# 2. 检查ideas表结构"
echo "sqlite3 data/research_dashboard_prod.db \"PRAGMA table_info(ideas);\""
echo ""
echo "# 3. 检查collaborators表的level字段"
echo "sqlite3 data/research_dashboard_prod.db \"PRAGMA table_info(collaborators);\" | grep level"
echo ""
echo "# 4. 查看部署日志中的迁移部分"
echo "grep -A10 -B5 \"v1.17\" /var/log/research-dashboard-deploy.log"
echo ""
echo "# 5. 手动执行迁移"
echo "ENVIRONMENT=production python3 migrations/migration.py"
echo ""
echo "# 6. 重启服务"
echo "systemctl restart research-backend"